'use client';

import { useState } from 'react';
import Image from 'next/image';
import FeedbackWidget from '@/app/components/FeedbackWidget';

export default function AboutClient() {
  const [feedbackOpen, setFeedbackOpen] = useState(false);

  return (
    <>
      <div className="d-flex flex-column flex-sm-row align-items-center align-items-sm-start gap-4 mb-5">
        <Image
          src="/radek-budar.jpg"
          alt="Radek Budař"
          width={140}
          height={140}
          className="rounded-circle flex-shrink-0"
          style={{ objectFit: 'cover' }}
          priority
        />
        <div>
          <h1 className="h3 mb-1">Radek Budař</h1>
          <p className="text-muted mb-2">Builder of Knockouts.in</p>
          <div className="d-flex flex-wrap gap-3">
            <a
              href="https://www.linkedin.com/in/radekbudar/"
              target="_blank"
              rel="noopener noreferrer"
              className="d-inline-flex align-items-center gap-1 text-decoration-none"
            >
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16" aria-hidden="true">
                <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854zm4.943 12.248V6.169H2.542v7.225zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248S2.4 3.226 2.4 3.934c0 .694.521 1.248 1.327 1.248zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016l.016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225z" />
              </svg>
              LinkedIn
            </a>
            <a
              href="mailto:radek.budar@gmail.com"
              className="d-inline-flex align-items-center gap-1 text-decoration-none"
            >
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16" aria-hidden="true">
                <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1zm13 2.383-4.708 2.825L15 11.105zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741M1 11.105l4.708-2.897L1 5.383z" />
              </svg>
              radek.budar@gmail.com
            </a>
          </div>
        </div>
      </div>

      <section className="mb-4">
        <h2 className="h5 mb-3">The story behind Knockouts.in</h2>
        <p>
          Hi, I&apos;m Radek — a tech guy who loves sports and data. When FIFA announced the expanded
          48-team World Cup format with its complex best third-placed team rules and qualification
          probabilities, I couldn&apos;t find a tracker that made it easy to follow. So I decided to build one.
        </p>
        <p>
          Knockouts.in is my end-to-end experiment in vibe coding — designing, building, and shipping
          a real web app from scratch: live standings, knockout bracket, Monte Carlo simulations,
          a pick&apos;em prediction game, and more. It&apos;s been a fun ride and the World Cup hasn&apos;t even
          started yet.
        </p>
        <p>
          If something&apos;s broken, confusing, or you just want to say hi — I&apos;d love to hear from you.
        </p>
      </section>

      <section className="mb-4">
        <h2 className="h5 mb-3">How the standings and probabilities are computed</h2>
        <p>
          Knockouts.in tracks the FIFA World Cup 2026 in real time — group standings, fixtures,
          the knockout bracket, and the qualification odds for every one of the 48 teams. The
          numbers you see don&apos;t come from a third-party feed; they&apos;re generated by a probability
          engine I built from scratch.
        </p>
        <p>
          After every match, the engine enumerates <strong>every remaining outcome combination</strong>{' '}
          in the group — each remaining game can end as a win, draw or loss with various score
          lines. For each combination it computes the final standings using FIFA&apos;s exact
          tie-breakers (points, head-to-head, goal difference, goals scored, fair-play points,
          FIFA ranking). Aggregating across all combinations gives the precise probability that
          each team finishes 1st, 2nd, 3rd or 4th — no Monte Carlo approximation, no missing
          edge cases. The same enumeration also drives the <strong>best-third-placed</strong>{' '}
          table, which compares thirds across all 12 groups to show what each team needs to grab
          one of the eight knockout spots.
        </p>
      </section>

      <section className="mb-4">
        <h2 className="h5 mb-3">Where the AI comes in</h2>
        <p>
          Raw probabilities are useful, but a list like <em>&ldquo;0.7% — beat Mexico by 4+ goals
          AND a draw between Czech Republic and Korea&rdquo;</em> isn&apos;t easy to read. So after the
          engine runs, every group&apos;s scenarios get fed to an AI language model
          (Anthropic&apos;s Claude), which writes a short, plain-English analysis: who has the best
          chance of advancing, where the real tension is, and which specific results would shift
          the picture.
        </p>
        <p>
          The AI never decides outcomes or invents numbers — its job is purely to translate the
          engine&apos;s exact probabilities into readable sports journalism. Every team page, group
          page and the headlines on the home page are regenerated automatically whenever a new
          result is entered.
        </p>
      </section>

      <section className="mb-4">
        <h2 className="h5 mb-3">Match data is entered by hand</h2>
        <p>
          There is no scraping pipeline behind this site. Every score, yellow card and red card
          you see was entered manually after I watched (or at least followed) the match.
          That&apos;s slower than scraping, but it means the probabilities and AI analyses you read
          are based on data I have personally verified. If something looks wrong, it&apos;s my
          mistake — and an email at{' '}
          <a href="mailto:support@knockouts.in">support@knockouts.in</a> away from being fixed.
        </p>
      </section>

      <button
        className="btn btn-primary"
        onClick={() => setFeedbackOpen(true)}
      >
        Send Feedback
      </button>

      <FeedbackWidget open={feedbackOpen} onClose={() => setFeedbackOpen(false)} />
    </>
  );
}
