import { ImageResponse } from 'next/og';

// Dynamic favicon — generated by next/og at build time and served as /icon.
// Pixelated soccer-ball-on-blue look that ties into the brand color.
export const runtime = 'nodejs';
export const size = { width: 64, height: 64 };
export const contentType = 'image/png';

export default function Icon() {
  return new ImageResponse(
    (
      <div
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          background: '#0a2540',
          color: '#ffd84d',
          fontSize: 38,
          fontWeight: 800,
          fontFamily: 'system-ui, -apple-system, sans-serif',
          borderRadius: 12,
        }}
      >
        K
      </div>
    ),
    { ...size },
  );
}
